/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package model.asn1.datatypes;

import org.openmuc.jasn1.ber.types.BerOctetString;


public class AddressString extends BerOctetString {

    private static final long serialVersionUID = 1L;

    public AddressString() {
    }

    public AddressString(byte[] value) {
        super(value);
    }

}
