/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package model.asn1.datatypes;


public class ISDNAddressString extends AddressString {

    private static final long serialVersionUID = 1L;

    public ISDNAddressString() {
    }

    public ISDNAddressString(byte[] value) {
        super(value);
    }

}
